INCS_PATH=-I..\opencv\include
LIBS_PATH=-L..\opencv\lib
CFLAGS=-lopencv_highgui2410 -lopencv_core2410 -lopencv_imgproc2410
all:
	g++ main.cpp $(INCS_PATH) $(LIBS_PATH) $(CFLAGS) -o main
run:
	main.exe
clean:
	rm main.exe